baseURL = "https://zestfuldata.com/"
languageCode = "en-us"
title = "Zestful Data"
theme = "zestful"
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
