version: 2.1
executors:
  node:
    docker:
      - image: cimg/node:24.4.1
  hugo:
    docker:
      - image: hugomods/hugo:0.147.5
jobs:
  lint:
    executor: node
    steps:
      - checkout
      - run:
          name: Download npm packages
          command: npm install
      - run:
          name: Check formatting
          command: ./dev-scripts/check-formatting
      - run:
          name: Run linter
          command: ./dev-scripts/lint
  build:
    executor: hugo
    steps:
      - checkout
      - run:
          name: Install bash
          command: apk add --no-cache bash
      - run:
          name: Build site
          command: ./dev-scripts/build
      - run:
          name: Write runtime config
          command: |
            if [[ -z "${BACKEND_URL:-}" ]]; then
              echo "BACKEND_URL must be set for the CI build."
              exit 1
            fi
            ./dev-scripts/write-config
      - persist_to_workspace:
          root: ./
          paths:
            - public
            - netlify.toml
  publish_draft:
    executor: node
    resource_class: small
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Install netlify CLI
          command: npm install netlify-cli@23.7.3 --save-dev
      - run:
          name: Print netlify version
          command: ./node_modules/.bin/netlify version
      - run:
          name: Deploy a live draft
          command: ./node_modules/.bin/netlify deploy --dir=public --site="${NETLIFY_SITE_ID}"
  deploy:
    executor: node
    resource_class: small
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Install netlify CLI
          command: npm install netlify-cli@23.7.3 --save-dev
      - run:
          name: Print netlify version
          command: ./node_modules/.bin/netlify version
      - run:
          name: Deploy to production
          command: ./node_modules/.bin/netlify deploy --dir=public --site="${NETLIFY_SITE_ID}" --prod
workflows:
  version: 2
  test_deploy:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - publish_draft:
          requires:
            - build
          filters:
            branches:
              ignore: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
